// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package internal

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjsonB75396bcDecodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal(in *jlexer.Lexer, out *EventList) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		in.Skip()
		*out = nil
	} else {
		in.Delim('[')
		if *out == nil {
			if !in.IsDelim(']') {
				*out = make(EventList, 0, 1)
			} else {
				*out = EventList{}
			}
		} else {
			*out = (*out)[:0]
		}
		for !in.IsDelim(']') {
			var v1 Event
			(v1).UnmarshalEasyJSON(in)
			*out = append(*out, v1)
			in.WantComma()
		}
		in.Delim(']')
	}
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB75396bcEncodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal(out *jwriter.Writer, in EventList) {
	if in == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
		out.RawString("null")
	} else {
		out.RawByte('[')
		for v2, v3 := range in {
			if v2 > 0 {
				out.RawByte(',')
			}
			(v3).MarshalEasyJSON(out)
		}
		out.RawByte(']')
	}
}

// MarshalJSON supports json.Marshaler interface
func (v EventList) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB75396bcEncodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v EventList) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB75396bcEncodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *EventList) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB75396bcDecodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *EventList) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB75396bcDecodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal(l, v)
}
func easyjsonB75396bcDecodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal1(in *jlexer.Lexer, out *Event) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "uuid":
			out.UUID = string(in.String())
		case "title":
			out.Title = string(in.String())
		case "start":
			out.Start = string(in.String())
		case "end":
			out.End = string(in.String())
		case "description":
			out.Description = string(in.String())
		case "ownerid":
			out.OwnerID = string(in.String())
		case "notifyin":
			out.NotifyIn = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjsonB75396bcEncodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal1(out *jwriter.Writer, in Event) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"uuid\":"
		out.RawString(prefix[1:])
		out.String(string(in.UUID))
	}
	{
		const prefix string = ",\"title\":"
		out.RawString(prefix)
		out.String(string(in.Title))
	}
	{
		const prefix string = ",\"start\":"
		out.RawString(prefix)
		out.String(string(in.Start))
	}
	{
		const prefix string = ",\"end\":"
		out.RawString(prefix)
		out.String(string(in.End))
	}
	{
		const prefix string = ",\"description\":"
		out.RawString(prefix)
		out.String(string(in.Description))
	}
	{
		const prefix string = ",\"ownerid\":"
		out.RawString(prefix)
		out.String(string(in.OwnerID))
	}
	{
		const prefix string = ",\"notifyin\":"
		out.RawString(prefix)
		out.String(string(in.NotifyIn))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v Event) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjsonB75396bcEncodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v Event) MarshalEasyJSON(w *jwriter.Writer) {
	easyjsonB75396bcEncodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *Event) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjsonB75396bcDecodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *Event) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjsonB75396bcDecodeGithubComF0m41h4u7GoHwHw12131415CalendarInternal1(l, v)
}
